import{_ as r}from"./plugin-vue_export-helper-DlAUqK2U.js";import{r as i,o as d,c as s,b as e,a,w as n,d as l,e as o}from"./app-DaBZCpA_.js";const c={},p=e("h1",{id:"android-错误总结",tabindex:"-1"},[e("a",{class:"header-anchor",href:"#android-错误总结"},[e("span",null,"Android 错误总结")])],-1),u={class:"table-of-contents"},h=l(`<h2 id="1-sync-时错误" tabindex="-1"><a class="header-anchor" href="#1-sync-时错误"><span>1. Sync 时错误</span></a></h2><p>Sync 时错误：<code>Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply</code>。</p><p>解决方法：在项目的 <code>gradle.properties</code> 中加入下面的代码。</p><div class="language-properties" data-ext="properties" data-title="properties"><pre class="language-properties"><code><span class="token key attr-name">android.overridePathCheck</span><span class="token punctuation">=</span><span class="token value attr-value">true</span>
</code></pre></div><h2 id="2-调试失败" tabindex="-1"><a class="header-anchor" href="#2-调试失败"><span>2. 调试失败</span></a></h2><p>无法启动 ADB 服务，持续重启 ADB demand。</p><p>解决方法：如果报错 <code>Adb connection Error: 远程主机强迫关闭了一个现有的连接。</code> 就是端口被占用，可能已经启动了另一个 ADB。</p><p>如果出现 <code>&quot;Cannot reach ADB server, attempting to reconnect.&quot;</code>，则表明 WiFi 调试与 ADB 冲突，需要搜索并关闭 <code>Enable adb mDNS for wireless debugging</code>。</p><h2 id="3-空指针异常" tabindex="-1"><a class="header-anchor" href="#3-空指针异常"><span>3. 空指针异常</span></a></h2>`,9);function m(g,y){const t=i("router-link");return d(),s("div",null,[p,e("nav",u,[e("ul",null,[e("li",null,[a(t,{to:"#1-sync-时错误"},{default:n(()=>[o("1. Sync 时错误")]),_:1})]),e("li",null,[a(t,{to:"#2-调试失败"},{default:n(()=>[o("2. 调试失败")]),_:1})]),e("li",null,[a(t,{to:"#3-空指针异常"},{default:n(()=>[o("3. 空指针异常")]),_:1})])])]),h])}const b=r(c,[["render",m],["__file","android-errors.html.vue"]]),A=JSON.parse('{"path":"/android/basic/android-errors.html","title":"Android 错误总结","lang":"zh-CN","frontmatter":{"description":"Android 错误总结 1. Sync 时错误 Sync 时错误：Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply。 解决方法：在项目的 gradle.properties 中加入下面的代码。 2. 调试失败 无法启动 ADB ...","head":[["meta",{"property":"og:url","content":"https://blog.alexsun.top/vuepress-frontend-notes/vuepress-frontend-notes/android/basic/android-errors.html"}],["meta",{"property":"og:site_name","content":"前端笔记"}],["meta",{"property":"og:title","content":"Android 错误总结"}],["meta",{"property":"og:description","content":"Android 错误总结 1. Sync 时错误 Sync 时错误：Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply。 解决方法：在项目的 gradle.properties 中加入下面的代码。 2. 调试失败 无法启动 ADB ..."}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:locale","content":"zh-CN"}],["meta",{"property":"og:updated_time","content":"2024-05-04T11:44:04.000Z"}],["meta",{"property":"article:author","content":"鸭梨"}],["meta",{"property":"article:modified_time","content":"2024-05-04T11:44:04.000Z"}],["script",{"type":"application/ld+json"},"{\\"@context\\":\\"https://schema.org\\",\\"@type\\":\\"Article\\",\\"headline\\":\\"Android 错误总结\\",\\"image\\":[\\"\\"],\\"dateModified\\":\\"2024-05-04T11:44:04.000Z\\",\\"author\\":[{\\"@type\\":\\"Person\\",\\"name\\":\\"鸭梨\\",\\"url\\":\\"https://blog.alexsun.top/\\"}]}"]]},"headers":[{"level":2,"title":"1. Sync 时错误","slug":"1-sync-时错误","link":"#1-sync-时错误","children":[]},{"level":2,"title":"2. 调试失败","slug":"2-调试失败","link":"#2-调试失败","children":[]},{"level":2,"title":"3. 空指针异常","slug":"3-空指针异常","link":"#3-空指针异常","children":[]}],"git":{"createdTime":1680144064000,"updatedTime":1714823044000,"contributors":[{"name":"Sun-ZhenXing","email":"1006925066@qq.com","commits":1}]},"readingTime":{"minutes":0.48,"words":144},"filePathRelative":"android/basic/android-errors.md","localizedDate":"2023年3月30日","autoDesc":true}');export{b as comp,A as data};
